### ISSUE TITLE
bug for LruCacheStore

### ISSUE THREAD

**Issue by droplet-js** [tiagohm/restio#14]
restio: ^0.7.1
```
https://www.xxxx.com/xxxx
GET
0
200 OK
12
x-powered-by: ASP.NET
set-cookie: ASP.NET_SessionId=s03uud1wa3gz2oww21zj45rl; path=/; HttpOnly
date: Sat, 09 May 2020 11:53:26 GMT
content-encoding: gzip
vary: Accept-Encoding
content-length: 831
x-aspnet-version: 4.0.30319
content-type: text/xml; charset=utf-8
server: Microsoft-IIS/7.5
cache-control: CacheControl { noCache: false, noStore: false, maxAge: 24:00:00.000000,  maxStale: null, minFresh: null, isPrivate: false, isPublic: false,  noTransform: false, immutable: false, mustRevalidate: false,  onlyIfCached: false }
Restio-Sent-Millis: 1589025206182
Restio-Received-Millis: 1589025206395
```

```
cache-control: CacheControl { noCache: false, noStore: false, maxAge: 24:00:00.000000,  maxStale: null, minFresh: null, isPrivate: false, isPublic: false,  noTransform: false, immutable: false, mustRevalidate: false,  onlyIfCached: false }
```

**Comment by droplet-js** [comment]
only create 7fdc6206ec38561548a1653ad5ae6636.0.tmp and 7fdc6206ec38561548a1653ad5ae6636.1.tmp

7fdc6206ec38561548a1653ad5ae6636.0 and 7fdc6206ec38561548a1653ad5ae6636.1 doesn't create

**Comment by droplet-js** [comment]
restore cache keyExtractor supported

**Comment by tiagohm** [comment]
You close the response calling `await response.close()` after executing the request?

**Comment by droplet-js** [comment]
> You close the response calling `await response.close()` after executing the request?

why not autoclose?

eg.
```dart
    final cacheStream = ResponseStream(
      response.body.data,
      onData: cacheSink.add,
      onDone: () => response.close();// or cacheStream.close(), cacheSink.close()
      onError: (e, stackTrace) async {
        // await cacheRequest.abort();
        cacheSink.addError(e, stackTrace);
      },
      onClose: () async {
        await cacheSink.close();
      },
    );
```

**Comment by droplet-js** [comment]
```
I/flutter (10695): FileSystemException: Cannot open file, path = '/storage/emulated/0/Android/data/com.example.app/cache/api/yy3g/fe3f87e8fca0c6968dc645317a6d0809.0' (OS Error: No such file or directory, errno = 2)
I/flutter (10695): #0      _File.throwIfError (dart:io/file_impl.dart:645:7)
I/flutter (10695): #1      _File.openSync (dart:io/file_impl.dart:489:5)
I/flutter (10695): #2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)
I/flutter (10695): #3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
I/flutter (10695): #4      LruCacheStore.get (package:restio/src/core/cache/lru_cache_store.dart:459:54)
I/flutter (10695): #5      Cache._get (package:restio/src/core/cache/cache.dart:95:30)
I/flutter (10695): #6      CacheInterceptor._execute (package:restio/src/core/cache/cache_interceptor.dart:23:40)
I/flutter (10695): #7      CacheInterceptor.intercept (package:restio/src/core/cache/cache_interceptor.dart:10:18)
I/flutter (10695): #8      InterceptorChain.proceed (package:restio/src/core/internal/interceptor_chain.dart:34:34)
I/flutter (10695): #9      BridgeInterceptor.intercept (package:restio/src/core/internal/bridge_interceptor.dart:28:34)
I/flutter (10695): #10     InterceptorChain.proceed (package:restio/src/core/internal/interceptor_chain.dart:34:34)
I/flutter (10695): #11     CookieInterceptor.intercept (package:restio/src/core/internal/cookie_interceptor.dart:43:34)
```

**Comment by tiagohm** [comment]
> why not autoclose?

`onDone` is sync and `.close()` is async, because of this, the easiest way I found to close and persist the cache is calling `response.close()` directly.
